In [32]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [33]:
# importing libraries  
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  

In [34]:
#importing datasets  
data_set= pd.read_csv('/content/drive/MyDrive/ML Dataset/AninditaDataset.csv') 

In [35]:
print(data_set)

     Gender  Age  Result of HSC  Result of SSC  Year of Enrollment  \
0    Female   27           4.47           3.27                2020   
1      Male   27           4.47           4.67                2019   
2    Female   20           4.33           5.00                2019   
3    Female   24           4.83           3.58                2020   
4    Female   30           4.50           3.89                2020   
..      ...  ...            ...            ...                 ...   
995  Female   19           4.89           3.40                2021   
996    Male   24           4.67           3.83                2022   
997  Female   26           3.75           3.15                2021   
998    Male   23           4.47           4.67                2018   
999    Male   23           4.33           4.72                2019   

     Certifications Institution            Discipline Family Dependency  \
0              3.75        UITS          Art & Design               Yes   
1        

In [36]:
data_set.shape

(1000, 14)

In [37]:
col_names = ['Gender', 'Age', 'Result of HSC', 'Result of SSC', 'Year of Enrollment', 'Certifications', 'Institution', 'Discipline', 'Family Dependency', 
'Applied Loan Amount', 'Duration of Loan', 'Approved Loan Amount', 'NOC from University', 'Approved']
data_set.columns = col_names
col_names

['Gender',
 'Age',
 'Result of HSC',
 'Result of SSC',
 'Year of Enrollment',
 'Certifications',
 'Institution',
 'Discipline',
 'Family Dependency',
 'Applied Loan Amount',
 'Duration of Loan',
 'Approved Loan Amount',
 'NOC from University',
 'Approved']

In [38]:
col_names = ['Gender', 'Age', 'Result of HSC', 'Result of SSC', 'Year of Enrollment', 'Certifications', 'Institution', 'Discipline', 'Family Dependency', 
'Applied Loan Amount', 'Duration of Loan', 'Approved Loan Amount', 'NOC from University', 'Approved']
for col in col_names:
  print(data_set[col].value_counts())

Female    522
Male      478
Name: Gender, dtype: int64
20    93
27    91
29    87
19    79
23    79
30    78
24    76
28    74
21    73
22    73
18    66
26    66
25    65
Name: Age, dtype: int64
5.00    46
3.75    44
4.09    44
4.89    44
4.67    43
4.50    42
4.40    41
3.67    40
3.83    38
4.15    38
3.52    38
4.33    38
4.97    37
4.27    36
3.33    36
4.56    36
4.47    34
3.15    31
3.40    30
3.00    29
4.72    29
3.89    29
3.46    28
3.09    27
4.00    26
3.97    25
3.27    25
4.83    24
3.58    22
Name: Result of HSC, dtype: int64
3.97    46
4.47    44
3.58    40
4.15    39
4.27    39
4.50    39
3.27    38
3.89    37
3.75    37
3.40    37
4.00    36
4.89    36
4.33    35
4.56    35
5.00    35
3.83    34
3.09    33
3.33    33
4.83    33
4.67    32
4.97    32
4.09    32
4.40    32
3.52    31
3.67    30
3.46    30
4.72    28
3.00    24
3.15    23
Name: Result of SSC, dtype: int64
2019    222
2020    219
2021    211
2022    184
2018    164
Name: Year of Enrollment, dtype: int64

In [39]:
data_set['Approved'].value_counts()

No     694
Yes    306
Name: Approved, dtype: int64

In [40]:
data_set.isnull().sum()

Gender                  0
Age                     0
Result of HSC           0
Result of SSC           0
Year of Enrollment      0
Certifications          0
Institution             0
Discipline              0
Family Dependency       0
Applied Loan Amount     0
Duration of Loan        0
Approved Loan Amount    0
NOC from University     0
Approved                0
dtype: int64

In [41]:
x = data_set.drop(['Approved'], axis=1)
y = data_set['Approved']

In [42]:
x

Gender  Age  Result of HSC  Result of SSC  Year of Enrollment  \
0    Female   27           4.47           3.27                2020   
1      Male   27           4.47           4.67                2019   
2    Female   20           4.33           5.00                2019   
3    Female   24           4.83           3.58                2020   
4    Female   30           4.50           3.89                2020   
..      ...  ...            ...            ...                 ...   
995  Female   19           4.89           3.40                2021   
996    Male   24           4.67           3.83                2022   
997  Female   26           3.75           3.15                2021   
998    Male   23           4.47           4.67                2018   
999    Male   23           4.33           4.72                2019   

     Certifications Institution            Discipline Family Dependency  \
0              3.75        UITS          Art & Design               Yes   
1              3.33         JNU           Mathematics                No   
2              3.89        AIUB           Mathematics               Yes   
3              3.89         UIU              Business                No   
4              3.15        RUET  Education & Teaching               Yes   
..              ...         ...                   ...               ...   
995            3.58        KUET           Programming               Yes   
996            3.97         IUB      Computer Science                No   
997            3.00        MIST          Art & Design                No   
998            3.67         NSU              Business                No   
999            3.15         JNU           Mathematics               Yes   

     Applied Loan Amount  Duration of Loan  Approved Loan Amount  \
0                1598000                 3                375000   
1                 472000                 3                300000   
2                 472000                 4                330000   
3                1520000                 2                300000   
4                1215000                 2                530000   
..                   ...               ...                   ...   
995              1400000                 3                290000   
996              2429700                 2                220000   
997              1598000                 3                580000   
998              1520000                 2                250000   
999               472000                 4                440000   

    NOC from University  
0                   Yes  
1                    No  
2                    No  
3                   Yes  
4                    No  
..                  ...  
995                 Yes  
996                 Yes  
997                  No  
998                  No  
999                  No  

[1000 rows x 13 columns]

In [43]:
y

0      Yes
1       No
2      Yes
3      Yes
4       No
      ... 
995     No
996     No
997     No
998    Yes
999     No
Name: Approved, Length: 1000, dtype: object

In [44]:
pip install --upgrade category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [45]:
import category_encoders as ce

In [46]:
# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0) 

In [47]:
x_train.shape, x_test.shape

((750, 13), (250, 13))

In [48]:
# Transform string value to int value

encoder = ce.OrdinalEncoder(cols= ['Gender', 'Institution', 'Discipline', 'Family Dependency', 'NOC from University'])

x_train = encoder.fit_transform(x_train)
x_test = encoder.transform(x_test)

In [49]:
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test) 

Decision Tree

In [50]:
#Fitting Decision Tree classifier to the training set  
from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [51]:
#Predicting the test set result  
y_pred= classifier.predict(x_test)  
print(y_pred)

['Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No'
 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes'
 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'Yes'
 'No' 'No' 'No' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes'
 'No' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'No' 'No'
 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes'

In [56]:
def getClassificationReport(cm):
  TP = cm[0][0]
  TN = cm[1][1]
  FN = cm[0][1]
  FP = cm[1][0]
  SN = TP/(TP+FN)
  SP= TN/(TN+FP)
  ACC =(TP+TN)/(TP+TN+FP+FN)
  PRE = TP/(FP+TP)
  F1 = (2*PRE*SN)/(PRE+SN)
  MCC = (TP*TN - FP*FN) / (((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))**(1/2))
  return SN,SP,ACC,MCC,F1


In [57]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)
print(cm)
getClassificationReport(cm)

[[146  24]
 [ 33  47]]


(0.8588235294117647, 0.5875, 0.772, 0.46170390425311114, 0.836676217765043)

In [66]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.772

Random Forest

In [60]:
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier_rfc= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier_rfc.fit(x_train, y_train) 

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [61]:
#Predicting the test set result  
y_pred_rfc = classifier_rfc.predict(x_test) 

In [65]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm_rfc= confusion_matrix(y_test, y_pred_rfc)  
print(cm_rfc)
getClassificationReport(cm_rfc)

[[148  22]
 [ 43  37]]


(0.8705882352941177, 0.4625, 0.74, 0.3659199251131987, 0.8199445983379501)

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_rfc)

0.74

Logistic Regression

In [69]:
from sklearn.linear_model import LogisticRegression  
classifier= LogisticRegression(random_state=0)  
classifier.fit(x_train, y_train) 

LogisticRegression(random_state=0)

In [70]:
#Predicting the test set result  
y_pred_lr= classifier.predict(x_test)

In [71]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm_lr= confusion_matrix(y_test, y_pred_lr)  
print(cm_lr)
getClassificationReport(cm_lr)

[[141  29]
 [ 32  48]]


(0.8294117647058824, 0.6, 0.756, 0.43388534222142894, 0.8221574344023324)

In [72]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_lr)

0.756

Support Vector Machine

In [73]:
from sklearn.svm import SVC  
classifier= SVC (random_state=0)  
classifier.fit(x_train, y_train) 

SVC(random_state=0)

In [74]:
#Predicting the test set result  
y_pred_svc= classifier.predict(x_test)

In [75]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm_svc= confusion_matrix(y_test, y_pred_svc)  
print(cm_svc)
getClassificationReport(cm_svc)

[[145  25]
 [ 30  50]]


(0.8529411764705882, 0.625, 0.78, 0.48651277256732783, 0.8405797101449276)

In [76]:
from sklearn.svm import SVC
svc_model = SVC()
svc_model.fit(x_train,y_train)
svc_model = svc_model.score(x_test, y_test)
svc_model

0.78

GaussianNB

In [77]:
from sklearn.naive_bayes import GaussianNB  
classifier= GaussianNB ()  
classifier.fit(x_train, y_train) 

GaussianNB()

In [78]:
#Predicting the test set result  
y_pred_GaussianNB= classifier.predict(x_test)

In [79]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm_GaussianNB= confusion_matrix(y_test, y_pred_GaussianNB)  
print(cm_GaussianNB)
getClassificationReport(cm_GaussianNB)

[[143  27]
 [ 23  57]]


(0.8411764705882353, 0.7125, 0.8, 0.546804191491934, 0.8511904761904762)

In [80]:
from sklearn.naive_bayes import GaussianNB
gauss_nb_model = GaussianNB()
gauss_nb_model.fit(x_train,y_train)
gauss_nb_model = gauss_nb_model.score(x_test, y_test)
gauss_nb_model

0.8

KNeighborsClassifier

In [85]:
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier ()  
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [86]:
#Predicting the test set result  
y_pred_KNeighborsClassifier= classifier.predict(x_test)

In [87]:
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm_KNeighborsClassifier= confusion_matrix(y_test, y_pred_KNeighborsClassifier)  
print(cm_KNeighborsClassifier)
getClassificationReport(cm_KNeighborsClassifier)

[[150  20]
 [ 42  38]]


(0.8823529411764706, 0.475, 0.752, 0.39491370343949855, 0.8287292817679558)

In [88]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
knn = knn.score(x_test,y_test)
knn

0.752